// Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace WebJobHealthNotifier.Api
{
    using Newtonsoft.Json;

    /// <summary>
    /// </summary>
    public partial interface IWebJobHealthNotifierApi : System.IDisposable
    {
        /// <summary>
        /// The base URI of the service.
        /// </summary>
        System.Uri BaseUri { get; set; }

        /// <summary>
        /// Gets or sets json serialization settings.
        /// </summary>
        JsonSerializerSettings SerializationSettings { get; }

        /// <summary>
        /// Gets or sets json deserialization settings.
        /// </summary>
        JsonSerializerSettings DeserializationSettings { get; }


        /// <summary>
        /// Gets the IDevices.
        /// </summary>
        IDevices Devices { get; }

        /// <summary>
        /// Gets the IFeeds.
        /// </summary>
        IFeeds Feeds { get; }

        /// <summary>
        /// Gets the ISubscriptions.
        /// </summary>
        ISubscriptions Subscriptions { get; }

    }
}
